version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    image: shpion-backend:latest   # tag locally-built image so it can be reused
    container_name: shpion-backend-prod
    restart: unless-stopped
    env_file:
      - ./backend-prod.env
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - shpion-net

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_LIVEKIT_URL=${VITE_LIVEKIT_URL}
    image: shpion-frontend:latest
    container_name: shpion-frontend-prod
    restart: unless-stopped
    ports:
      # Map container's 8080 to host's 8080. You can change the host port if needed.
      - "8080:8080"
    networks:
      - shpion-net

  caddy:
    image: caddy:2-alpine
    container_name: shpion-caddy-prod
    restart: unless-stopped
    volumes:
      - ./infra/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - shpion-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:15-alpine
    container_name: shpion-db-prod
    restart: unless-stopped
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    env_file:
      - ./backend-prod.env
    networks:
      - shpion-net
    # Note: Port 5432 is not exposed to the host for security.
    # The backend will connect to it via the internal docker network.

networks:
  shpion-net:
    driver: bridge

volumes:
  postgres_prod_data:
    driver: local 

  caddy_data:
    driver: local

  caddy_config:
    driver: local 