name: Deploy to Production

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Backend Docker image
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/shpion-backend

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Extract metadata for Frontend Docker image
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/shpion-frontend

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta_frontend.outputs.tags }}
          labels: ${{ steps.meta_frontend.outputs.labels }}
          build-args: |
            REACT_APP_API_URL=${{ vars.REACT_APP_API_URL }}
            REACT_APP_LIVEKIT_URL=${{ vars.REACT_APP_LIVEKIT_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Deploy to server
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > backend-prod.env
          echo "LIVEKIT_URL=${{ secrets.LIVEKIT_URL }}" >> backend-prod.env
          echo "LIVEKIT_API_KEY=${{ secrets.LIVEKIT_API_KEY }}" >> backend-prod.env
          echo "LIVEKIT_API_SECRET=${{ secrets.LIVEKIT_API_SECRET }}" >> backend-prod.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> backend-prod.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> backend-prod.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> backend-prod.env
          sudo docker-compose -f docker-compose.prod.yml pull
          sudo docker-compose -f docker-compose.prod.yml up -d --force-recreate
          
      - name: Clean up
        run: sudo docker image prune -af 